name: portifolio
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.2.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  
  cupertino_icons: ^1.0.2

  lottie: ^2.7.0
  adaptive_theme: ^3.4.1
  flutter_modular: ^6.3.2
  flutter_svg: ^2.0.9
  flutter_svg_provider: ^1.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/