name: portifolio
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  
  cupertino_icons: ^1.0.2

  lottie: ^3.1.2
  adaptive_theme: ^3.4.1
  flutter_modular: ^6.3.2
  flutter_svg: ^2.0.9
  flutter_svg_provider: ^1.0.7
  flip_card: ^0.7.0
  anchor_scroll_controller: ^0.4.4
  intl: ^0.19.0
  intl_utils: ^2.8.7
  shared_preferences: ^2.2.2
  url_launcher: ^6.2.5


dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/svg/
    - assets/lotties/
    - assets/projects/
    

flutter_intl:
  enabled: true
  class_name: S
  main_locale: en
  arb_dir: lib/core/l10n
  output_dir: lib/core/generated