name: Flutter Build and Deploy

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Debug
      run: ls -R

    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.16.1'

    - name: Install Dependencies
      run: flutter pub get

    - name: Build Flutter App
      run: flutter build web 
    
    - name: upload Web Build Files
      uses: actions/upload-artifact@v3
      with:
        name: web-release
        path: build/web

  deploy:
    name: Deploy Web Build
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Download Web Release
      uses: actions/download-artifact@v3
      with:
        name: web-release
      
    - name: Deploy to gh-pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./
