name: Flutter Build and Deploy

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.22.1'

    - name: Install Dependencies
      run: flutter pub get

    - name: Build Flutter App
      run: flutter build web --release
    
    - name: upload Web Build Files
      uses: actions/upload-artifact@v3
      with:
        name: web-release
        path: build/web
    
    - name: Deploy
      run: |
          cd build/web
          git init
          git config --global user.email nayronmoura@gmail.com
          git config --global user.name nayronmoura
          git status
          git remote add origin https://${{secrets.token}}@github.com/nayronmoura/nayronmoura.github.io.git
          git checkout -b gh-pages
          git add --all
          git commit -m "update"
          git push origin gh-pages -f
